[package]
name = "core"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
node = ["napi", "napi-derive"]
wasm = ["tsify", "wasm-bindgen"]

[dependencies]
swc_common = { version = "0.33.12" }
swc_ecmascript = { version = "0.237.17", features = ["parser", "visit"] }
swc_compiler_base = { version = "0.4.17" }
swc_error_reporters = { version = "0.17.12" }
anyhow = { workspaces = true }
serde_json = { workspace = true }
serde = { workspace = true }
rayon = "1.8.0"
lazy_static = "1.4.0"

napi = { workspace = true, optional = true }
napi-derive = { workspace = true, optional = true }

tsify = { version = "0.4.5", optional = true }
wasm-bindgen = { workspace = true, optional = true}
